/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as TrialsRouteImport } from './routes/trials'
import { Route as ApiPublicHooksRenewalRemindersRouteImport } from './routes/api/public/hooks/renewal-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialsRoute = TrialsRouteImport.update({
  id: '/trials',
  path: '/trials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRenewalRemindersRoute =
  ApiPublicHooksRenewalRemindersRouteImport.update({
    id: '/api/public/hooks/renewal-reminders',
    path: '/api/public/hooks/renewal-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/trials': typeof TrialsRoute
  '/api/public/hooks/renewal-reminders': typeof ApiPublicHooksRenewalRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/trials': typeof TrialsRoute
  '/api/public/hooks/renewal-reminders': typeof ApiPublicHooksRenewalRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/trials': typeof TrialsRoute
  '/api/public/hooks/renewal-reminders': typeof ApiPublicHooksRenewalRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/connect'
    | '/settings'
    | '/subscriptions'
    | '/trials'
    | '/api/public/hooks/renewal-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/connect'
    | '/settings'
    | '/subscriptions'
    | '/trials'
    | '/api/public/hooks/renewal-reminders'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/connect'
    | '/settings'
    | '/subscriptions'
    | '/trials'
    | '/api/public/hooks/renewal-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TrialsRoute: typeof TrialsRoute
  ApiPublicHooksRenewalRemindersRoute: typeof ApiPublicHooksRenewalRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trials': {
      id: '/trials'
      path: '/trials'
      fullPath: '/trials'
      preLoaderRoute: typeof TrialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/renewal-reminders': {
      id: '/api/public/hooks/renewal-reminders'
      path: '/api/public/hooks/renewal-reminders'
      fullPath: '/api/public/hooks/renewal-reminders'
      preLoaderRoute: typeof ApiPublicHooksRenewalRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TrialsRoute: TrialsRoute,
  ApiPublicHooksRenewalRemindersRoute: ApiPublicHooksRenewalRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
